apps/post/urls.py
from django.urls import path
from apps.post.views import Post

urlpatterns = [
    path('post/', Post.get_all_posts, name='post.all'),
    path('post/create/form/', Post.post_create_form_view, name='post.form'),
    path('post/create/validation/', Post.post_create, name="post.create"),
    path('post/filter/', Post.post_filter, name='post.filter'),
    path('post/update/form/<int:post_id>/', Post.post_update_form_view, name='post.update.form'),
    path('post/update/validation/<int:post_id>/', Post.post_update, name='post.update.validation'),
    path('post/delete/', Post.post_delete, name="post.delete"),
    path('post/search/', Post.get_all_post_by_category, name='post.by.category'),
    path('post/detail/', Post.get_post_detail, name='post.detail')
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', include('apps.home.urls')),
    path('', include('apps.post.urls')),
    path('', include('apps.category.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

apps/post/models.py
from django.db import models
import os


class Post(models.Model):
    """
    Post table model
    """
    title = models.CharField(max_length=100)
    content = models.TextField()
    slug = models.CharField(max_length=255)
    category = models.ForeignKey('PostCategory', null=True, blank=True, on_delete=models.DO_NOTHING)
    images = models.ImageField(upload_to=os.path.realpath('media/images/'), blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class PostComment(models.Model):
    """ Post comment table """

    # Status const
    STATUS_VISIBLE = 'visible'
    STATUS_HIDDEN = 'hidden'

    # Status choices
    STATUS_CHOICES = (
        (STATUS_VISIBLE, 'Visible'),
        (STATUS_HIDDEN, 'Hidden')
    )

    author_name = models.CharField(max_length=100)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField()
    status = models.CharField(max_length=20, default=STATUS_VISIBLE, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)


class PostCategory(models.Model):
    """ Post Category table """
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

apps/post/forms.py
from django import forms
from post.models import Post


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'images', ]

apps/post/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.defaultfilters import slugify
from django.core.paginator import Paginator
from apps.post.forms import CreatePostForm
from apps.post.model_helpers import handle_upload_file, get_file_name
from post.models import Post as PostModel, PostCategory
from django.db.models import Q
import json


class Post:

    def get_all_posts(self):
        """
        Retrieve all posts
        :return:
        """
        posts = PostModel.objects.all()
        return render(self, 'post/post.html', {
            'posts': posts
        })

    def post_create_form_view(self):
        categories = PostCategory.objects.all()
        form = CreatePostForm()
        return render(self, 'post/form.html', {
            'form': form,
            'categories': categories
        })

    def post_create(self, *args, **kwargs):
        if self.is_ajax() and self.method == 'POST':
            data = json.loads(self.body)
            if data['title'] is not None and len(data['title']) < 3:
                return JsonResponse({
                    'error_title_length': 'The title must have at least 3 characters'
                }, status=400)
            elif data['title'] is not None and len(data['title']) >= 3:
                check_if_title_exist = PostModel.objects.filter(title=data['title']).exists()
                if check_if_title_exist:
                    return JsonResponse({
                        'error_title_exist': f"The title {data['title']} exist ! Please provide another title"
                    }, status=400)

            if data['content'] is not None and len(data['content']) < 10:
                return JsonResponse({
                    'error_content_length': 'The content must have at least 10 characters'
                }, status=400)

            if data['images'] is not None:
                if data['category'] is not None and int(data['category']) > 0:
                    category = get_object_or_404(PostCategory, pk=int(data['category']))
                    PostModel.objects.create(title=data['title'],
                                             content=data['content'],
                                             slug=slugify(data['title']), images=get_file_name(data['images']),
                                             category=category, published=data['published'])
                else:
                    PostModel.objects.create(title=data['title'], content=data['content'],
                                             slug=slugify(data['title']), images=get_file_name(data['images']),
                                             published=data['published'])
            else:
                if data['category'] is not None and int(data['category']) > 0:
                    category = get_object_or_404(PostCategory, pk=int(data['category']))
                    PostModel.objects.create(title=data['title'],
                                             content=data['content'],
                                             slug=slugify(data['title']), images=get_file_name(data['images']),
                                             category=category, published=data['published'])
                else:
                    PostModel.objects.create(title=data['title'],
                                             content=data['content'],
                                             slug=slugify(data['title']), published=data['published'])

            return JsonResponse({
                'success': 'Le formulaire a bien été validé'
            }, status=200)
        else:
            return JsonResponse({
                'error_form': 'An error occured'
            }, status=400)

    def post_filter(self):
        """
        Filter post by post title OR category name
        :return:
        """
        if self.is_ajax() and self.method == 'POST':
            data = json.loads(self.body)
            if len(data['filter']) >= 3:
                posts = PostModel.objects.filter(Q(title__icontains=data['filter']) | Q(category__name__icontains=data['filter'])).values()
                return JsonResponse({
                    'data': list(posts)
                })
            elif not data['filter'] or len(data['filter']) < 1:
                posts = PostModel.objects.all().values()
                return JsonResponse({
                    'data_all': list(posts)
                })
        posts = PostModel.objects.all()
        return render(self, 'post/post_filter.html', {
            'posts': posts
        })

    def post_update_form_view(self, post_id):
        post = PostModel.objects.get(pk=post_id)
        categories = PostCategory.objects.all()
        return render(self, 'post/form_update.html', {
            'post': post,
            'categories': categories
        })

    def post_update(self, post_id, *args, **kwargs):
        if self.is_ajax() and self.method == 'POST':
            data = json.loads(self.body)
            print(data)
            if data['title'] is not None and len(data['title']) < 3:
                return JsonResponse({
                    'error_title_length': 'The title must have at least 3 characters'
                }, status=400)
            elif data['title'] is not None and len(data['title']) >= 3:
                get_old_title = PostModel.objects.filter(pk=post_id).values('title')
                for title in get_old_title:
                    if title['title'] != data['title']:
                        check_if_title_exists = PostModel.objects.filter(title=data['title']).exists()
                        if check_if_title_exists:
                            return JsonResponse({
                                'error_title_exist':  f"The title {data['title']} exist ! Please provide another title"
                            }, status=400)

            if data['content'] is not None and len(data['content']) < 10:
                return JsonResponse({
                    'error_content_length': 'The title must have at least 10 characters'
                }, status=400)

            if data['category'] is not None and int(data['category']) > 0:
                check_if_category_is_same = PostModel.objects.filter(pk=post_id).values('category')
                for category_value in check_if_category_is_same:
                    if int(category_value['category']) != int(data['category']):
                        PostModel.objects.filter(pk=post_id).update(title=data['title'], content=data['content'], category=int(data['category']))

            PostModel.objects.filter(pk=post_id).update(title=data['title'], content=data['content'])
            return JsonResponse({
                'success': 'Le formulaire a bien été validé'
            }, status=200)
        return JsonResponse({
            'error_form': 'An error occured'
        }, status=400)

    def post_delete(self):
        if self.is_ajax() and self.method == 'POST':
            data = json.loads(self.body)
            verify_if_post_exist = PostModel.objects.filter(pk=int(data['id'])).exists()
            if verify_if_post_exist is not True:
                return JsonResponse({
                    'error_not_exist_post': "Le post n'existe pas"
                })
            else:
                PostModel.objects.filter(pk=int(data['id'])).delete()
                return JsonResponse({
                    'success': 'Le post a bien été supprimé'
                })
        return JsonResponse({
            'error_form': 'An error occured'
        })

    def get_all_post_by_category(self):
        query_param = self.GET.get("name")
        data = PostModel.objects.filter(category__slug=query_param).all()

        paginator = Paginator(data, 1)
        page_number = self.GET.get('page')
        page_object = paginator.get_page(page_number)

        return render(self, 'post/post_all_by_category.html', {
            'posts': data,
            'category_name': query_param,
            'page_object': page_object
        })

    def get_post_detail(self):
        query_param = self.GET.get('title')
        data = PostModel.objects.filter(slug=query_param).values()
        return render(self, 'post/post_detail.html', {
            'data': data
        })

apps/post/templates/post/form.html
{% extends 'base.html' %}

{% block content %}

    <div id="post-create">
        <p class="alert"></p>
        <form action="{% url 'post.create' %}" id="post-form-create" data-current-route="{% url 'post.form' %}"
              data-route-redirect="{% url 'post.all' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div>
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}
            <div>
                <select name="category" id="id_categories">
                    <option value="0">-- Choose Category --</option>
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <input type="checkbox" name="published" id="published">
            </div>

            <button type="submit">Save</button>
        </form>
    </div>

{% endblock content %}

apps/post/templates/post/form_update.html
{% extends 'base.html' %}

{% block content %}
        <div id="post-create">
        <p class="alert"></p>
        <form action="{% url 'post.update.validation' post.id %}" id="post-form-update" data-current-route="{% url 'post.update.form' post.id %}"
              data-route-redirect="{% url 'post.update.form' post.id %}"
              method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="id_title">Title</label>
                <input type="text" name="title" id="id_title" value="{{ post.title }}">
            </div>
            <div>
                <label for="id_content">Content</label>
                <textarea name="content" id="id_content" cols="30" rows="10">{{ post.content|safe }}</textarea>
            </div>
            <div>
                <label for="id_images">Images</label>
                <input type="file" name="image" id="id_images">
            </div>
             <div>
                <select name="category" id="id_categories">
                    {% for category in categories %}
                        <option value="{{ category.id }}" {% if category.id == post.category_id %} selected {% else %} {% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <input type="checkbox" name="published" id="published" {% if post.published %} checked value="1" {% else %} value="0"{% endif %} />
                <label for="published">Publish post ?</label>
            </div>

            <button type="submit">Save</button>
        </form>
    </div>

{% endblock content %}

apps/post/templates/post/post.html
{% extends 'base.html' %}

{% block content %}

    <h1>Welcome to post page</h1>
    <table id="post-table" data-route-delete="{% url 'post.delete' %}">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Category</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody class="post-table">
            {% for post in posts %}
                <tr>
                    <td>{{ post.title }}</td>
                    {% if post.category %}
                        <td>{{ post.category.name }}</td>
                    {% else %}
                        <td>No category</td>
                    {% endif %}
                    <td>
                        <a href="{% url 'post.update.form' post.id %}">Modifier</a>
                        <button data-item-id="{{ post.id }}" type="submit" class="post-delete">Supprimer</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

apps/post/templates/post/post_all_by_category.html
{% extends 'base.html' %}

{% block content %}

    <div style="display: flex; width: 100%; justify-content: center; align-items: center; flex-direction: column">
        <div>
            <h1>Tous les {{ category_name }}</h1>
        </div>
        <div class="card-container card-container-4 unset-height-important">
        <a href="#" class="card-card card-not-animated border-rounded-35">
            <div class="card-img">
                <img src="../../../../media/images/emploi.jpg" alt="">
            </div>
            <div class="card-content">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aliquam consectetur corporis cupiditate ea, fugiat fugit harum impedit, magnam, nam nisi quae quo repudiandae! Dicta dolores exercitationem fugit minus veritatis!
                </p>
            </div>
        </a>
        <a href="#" class="card-card card-not-animated border-rounded-35">
            <div class="card-img">
                <img src="../../../../media/images/emploi.jpg" alt="">
            </div>
            <div class="card-content">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aliquam consectetur corporis cupiditate ea, fugiat fugit harum impedit, magnam, nam nisi quae quo repudiandae! Dicta dolores exercitationem fugit minus veritatis!
                </p>
            </div>
        </a>
        <a href="#" class="card-card card-not-animated border-rounded-35">
            <div class="card-img">
                <img src="../../../../media/images/emploi.jpg" alt="">
            </div>
            <div class="card-content">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aliquam consectetur corporis cupiditate ea, fugiat fugit harum impedit, magnam, nam nisi quae quo repudiandae! Dicta dolores exercitationem fugit minus veritatis!
                </p>
            </div>
        </a>
        <a href="#" class="card-card card-not-animated border-rounded-35">
            <div class="card-img">
                <img src="../../../../media/images/services-nationaux.jpg" alt="">
            </div>
            <div class="card-content">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aliquam consectetur corporis cupiditate ea, fugiat fugit harum impedit, magnam, nam nisi quae quo repudiandae! Dicta dolores exercitationem fugit minus veritatis!
                </p>
            </div>
        </a>
        <a href="#" class="card-card card-not-animated border-rounded-35">
            <div class="card-img">
                <img src="../../../../media/images/emploi.jpg" alt="">
            </div>
            <div class="card-content">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aliquam consectetur corporis cupiditate ea, fugiat fugit harum impedit, magnam, nam nisi quae quo repudiandae! Dicta dolores exercitationem fugit minus veritatis!
                </p>
            </div>
        </a>
    </div>
    </div>

    {# Pagination #}

    {% comment %}<div class="pagination">
        <span class="step-links">
            {% if page_object.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_object.previous_page_number }}">previous</a>
            {% endif %}
        </span>

        <span class="current">
            Page {{ page_oject.number }} of {{ page_object.paginator.num_pages }}.
        </span>

        {% if page_object.has_next %}
            <a href="?page={{ page_object.next_page_number }}">next</a>
            <a href="?page={{ page_object.paginator.num_pages }}">last &quot;</a>
        {% endif %} 
    </div> {% endcomment %}
{% endblock content %}

apps/post/templates/post/post_detail.html
{% extends 'base.html' %}

{% block content %}

    <section class="post-detail-container" id="post-detail">
        <div class="post-detail-bg-img">
        </div>
        <div class="post-detail-content">
            <div style="width: 100%; display: flex; justify-content: center; align-items: center; padding: 50px 0px">
                <h3 style="font-size: 2.5em">Test 2</h3>
            </div>
            <section class="post-detail-content-text">
                <div style="width: 70%; display: flex; justify-content: center; align-items: center;">
                    <article>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur beatae commodi dicta eaque et facere fugit iste itaque mollitia neque omnis perspiciatis praesentium, quidem quo recusandae rerum tempore totam ut?. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab animi commodi expedita itaque iure maxime minima numquam ratione suscipit voluptatem! Eius ex, quaerat? Alias, esse ipsum? Aperiam facere provident quos? Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet asperiores deserunt dolor ducimus, earum, eos esse et illum soluta temporibus tenetur ullam veritatis! Eligendi et eum nisi quasi sequi! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus expedita neque quae repudiandae! Accusamus accusantium amet eaque, eligendi eos eveniet ex hic, ipsa labore pariatur, sequi similique veniam voluptatem voluptatibus!
                    </article>
                </div>
            </section>
            <section class="post-detail-images-container">
                <div class="card-container card-container-3">
                    <div class="post-detail-image">
                    </div>
                    <div class="post-detail-image">
                    </div>
                    <div class="post-detail-image">
                    </div>
                </div>
            </section>

            {# Block users comments #}
            <section class="post-detail-comments-container">
                <div class="post-details-comments">
                    <div class="user-comments">
                        <div class="user-comment-img">
                            <img src="../../../../media/images/unknown.png" alt="">
                        </div>
                        <div class="user-comment-content">
                            <article>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas quidem reprehenderit tenetur totam ullam vitae. Aperiam et excepturi in nihil perspiciatis, quaerat. Atque cum eligendi eos, eum modi quidem sunt!
                            </article>
                        </div>
                    </div>
                    <div class="user-comments">
                        <div class="user-comment-img">
                            <img src="../../../../media/images/unknown.png" alt="">
                        </div>
                        <div class="user-comment-content">
                            <article>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas quidem reprehenderit tenetur totam ullam vitae. Aperiam et excepturi in nihil perspiciatis, quaerat. Atque cum eligendi eos, eum modi quidem sunt!
                            </article>
                        </div>
                    </div>
                    <div class="user-comments">
                        <div class="user-comment-img">
                            <img src="../../../../media/images/unknown.png" alt="">
                        </div>
                        <div class="user-comment-content">
                            <article>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas quidem reprehenderit tenetur totam ullam vitae. Aperiam et excepturi in nihil perspiciatis, quaerat. Atque cum eligendi eos, eum modi quidem sunt!
                            </article>
                        </div>
                    </div>
                </div>
            </section>

            <section class="post-detail-comment-form">
                <form action="#" id="post-detail-form-comment">
                    <textarea name="" id="" cols="30" rows="10" placeholder="Votre commentaire"></textarea>
                    <button type="submit">Commenter</button>
                </form>
            </section>
        </div>
    </section>

    {% comment %} {% for post in data %}
        <p>{{ post.content }}</p>

    {% endfor %} {% endcomment %}

{% endblock content %}

apps/post/templates/post/post_filter.html
{% extends 'base.html' %}

{% block content %}

    <h1>Filter posts</h1>

    <input data-category-route="{% url 'post.search.category' %}" data-route-filter="{% url 'post.filter' %}" type="text" name="filter_post" id="filter_post" placeholder="Type...">

    <ul id="list_posts">
        {% for post in posts %}
        <li>
            <a href="{% url 'post.search.category' %}?name={{ post.slug }}">{{ post.title }}</a>
        </li>
        {% endfor %}

    </ul>

{% endblock content %}